/*
 * XYZWriter.cpp
 *
 *  Created on: 01.03.2010
 *      Author: eckhardw
 */

#include "OutputWriter/XYZWriter.h"
#include "Writer.h"
#include <iomanip>
#include <sstream>
#include <vector>
#include <algorithm>


XYZWriter::XYZWriter() = default;

XYZWriter::~XYZWriter() = default;

void XYZWriter :: writeParticlesToFile(const std::string &filename, int iteration, const std::vector<Particle> &particles) {
    std::vector<Particle> particlesSorted = particles;
    std::sort(particlesSorted.begin(), particlesSorted.end(), [](Particle &p1, Particle &p2){return p1.getId() < p2.getId();});
    std::ofstream file;
    std::stringstream strstr;
    strstr << filename << "_" << std::setfill('0') << std::setw(4) << iteration << ".xyz";

    file.open(strstr.str().c_str());
    file << particles.size() << std::endl;
    file << "Generated by MolSim. See http://openbabel.org/wiki/XYZ_(format) for "
            "file format doku."
         << std::endl;


    for (const auto & particle : particles) {
        std::array<double, 3> x = particle.getX();
        file << "Ar ";
        file.setf(std::ios_base::showpoint);

        for (auto &xi: x) {
            file << xi << " ";
        }

        file << std::endl;
    }

  file.close();
}

