name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: RunTest
      run: |
        sudo apt install libxerces-c-dev
        mkdir build
        cmake -D BUILD_DOXYGEN=OFF -B build
        cd build
        make Tests
        ctest
      


